### PR TITLE
Update Runtime(s) to 23.08

### PR DESCRIPTION
**Pull request by Justinzobel**

### CODE REVIEW

**Comment by tsdgeos** [comment]
There's something fishy here, this one shows a warning dialog on startup while the one currently in flathub does not

**Comment by Justinzobel** [comment]
> There's something fishy here, this one shows a warning dialog on startup while the one currently in flathub does not

Interesting, what is the warning? Likely an issue with something that changed in the FreeDesktop runtime that's not compatible.

**Comment by Erick555** [comment]
I'm seeing this:

> There was an error executing the GnuPG configuration self-check for dirmngr:
> The configuration file is invalid.
> You might want to execute "gpgconf --check-options dirmngr" on the command line.

It happens because dirmngr is no longer in runtime (it was in 22.08):
```
[📦 org.kde.kleopatra ~]$ gpgconf --check-options dirmngr
gpgconf: error running '/usr/bin/dirmngr': probably not installed
dirmngr:Network:/usr/bin/dirmngr:0:0:
```

Apparently dirmngr isn't in runtime because it [grows new dependencies](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15732), not existing in runtime.

Eventually this needs to be fixed in runtime although you my try bundling gnupg in the app for now.

**Comment by Erick555** [comment]
The fix is on its way: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/15869

**Comment by Erick555** [comment]
freedesktop-sdk 23.08 is fixed on flathub. Now KDE 5-15.23.08 needs rebuild.

**Comment by tsdgeos** [comment]
oh damn, i just triggered one 4 hours ago :D  

Wonder if it's late enough :D  https://buildbot.flathub.org/#/apps/org.kde.Sdk~2F5.15-23.08

Let's wait a bit more

**Comment by Erick555** [comment]
It could be enough - check if `/usr/bin/dirmngr` is present after rebuild.

**Comment by Erick555** [comment]
I checked and binary is there. Please re-test the app, it should be good to go.

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
bot, build

**Comment by Erick555** [comment]
some transient error with gpgme source. I can download the file manually just fine.

**Comment by Erick555** [comment]
I can confirm no warnings at startup - app self tests pass.

**Pull request merged**
