### PR TITLE
Temporarily remove --socket=gpg-agent

### PR DESCRIPTION
**Pull request by travier**
See: https://github.com/flathub/org.kde.kleopatra/issues/1

### CODE REVIEW

**Comment by travier** [comment]
@ImBearChild Can you try this one? Thanks

**Comment by ImBearChild** [comment]
> @ImBearChild Can you try this one? Thanks

This build works for me. By the way, should we add some additional notification to let users know that flatpak version of kleopatra needs an running `gpg-agent` from host to work?

**Comment by travier** [comment]
> This build works for me. By the way, should we add some additional notification to let users know that flatpak version of kleopatra needs an running `gpg-agent` from host to work?

Can you make a PR to add a README to this repo with this info and also file a bug in KDE bugzilla's? Thanks!

**Comment by ImBearChild** [comment]
sure

**Pull request merged**
